### ISSUE TITLE
Use object get so @map works with nested fields

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher-schema-directives#8]
```firstName: String @map("profile.first_name")```

^ This should work

**Comment by kations** [comment]
Hi Theodor,

Seems not to work, I get the following error: Syntax Error: Expected Name, found String "content.name".

Schema looks like: 
Example @mongo(name: "example") {
  name: String @map("content.name")
}

Version:
cultofcoders:grapher@1.3.12
cultofcoders:grapher-schema-directives@0.1.8

Cheers

**Comment by theodorDiaconu** [comment]
@kations it is `@map not @Map`
